export const videoNodeNames = [
    'YTD-GRID-VIDEO-RENDERER',
    'YTD-VIDEO-RENDERER',
    'YTD-COMPACT-VIDEO-RENDERER',
    'YTD-RICH-GRID-VIDEO-RENDERER',
    'YTD-PLAYLIST-RENDERER',
    'YTD-MOVIE-RENDERER',
    'YTD-CHANNEL-RENDERER',
    'YTD-VIDEO-OWNER-RENDERER',
];
